### ISSUE TITLE
Pré-requisito de componente curricular

### ISSUE THREAD

**Issue by letMarchezi** [letMarchezi/isf-pibd#8]
Acredito que isso funciona assim: 1 turma possui N pré requisitos. Não são exatamente conjuntos de turmas que dependem de vários pré requisitos. Acho que o auto relacionamento buga um pouco nossa cabeça, mas por exemplo, temos uma matéria X que depende da matéria Y, Z, etc. Pode ser que duas matérias tenham o mesmo pre-req, mas acho que daria pra representar isso como 1:N facilmente. O que acham?
Acho que nomear o relacionamento como a prof recomendou ajuda nisso. então tbm sugiro adicionar nome no relacionamento.

![is1](https://github.com/letMarchezi/isf-pibd/assets/39420862/9b4800d5-ec41-4468-a9ce-2369a5c0cfbf)

**Comment by DanielKenichi** [comment]
Hmm acho que da para fazer a relação de pré-requisito direto com a turma sim. Mas não continuaria sendo N:M? Pq tipo, como comentou, acho que uma matéria pode ser pré-requisito de varias turmas

**Comment by letMarchezi** [comment]
Não não, não tem relação de pré-requisito com turma. É matéria com matéria. Só que a gente lê assim: n matéria tem requisitos com m matérias, ou 1 matéria tem requisito com m matérias. Na vida real é o segundo caso. Pode ser q a materia x e a materia y tenham  os mesmos pre requisitos, mas aí não importa kkkkk, porque são coisas diferentes. Não é o conjunto de 2 matérias ou mais que têm pre requisitos, é UMA matéria. Por isso deveria ser 1:m, entendeu?
Se ficar estranho, lê de novo, pq acho que a leitura q a gnt tava fazendo do DER tava errada. tem que lembrar como funciona auto relacionamento.

**Comment by letMarchezi** [comment]
Por isso é essencial ter nome no auto relacionamento. Em uma ponta, UM componente depende de M componentes. Lendo do outro lado, é tipo M componentes são dependência de UM componente.

**Comment by DanielKenichi** [comment]
Hmmm acho que entendi a questão da leitura, mas eu não entendi ainda como que ficaria o mapeamento disso aí, tipo, no 1:M, teria uma FK na entidade que no relacionamento tem cardinalidade M, indicando que uma matéria X é pré-requisito de uma matéria Y. Mas se essa matéria X pode ser pré-requisito de mais de uma matéria, o mapeamento precisaria de uma tabela para relacionar isso, e normalmente isso nasce de um N:M não?

**Comment by DanielKenichi** [comment]
Tipo, a leitura que eu acho que seria no nosso caso seria "Uma matéria tem vários pré-requisitos, e pode ser pré-requisito de mais de uma matéria"

**Comment by letMarchezi** [comment]
Entendi, acho que é N:M mesmo porque podem ter varias dependencias iguais
