### ISSUE TITLE
Situação final do aluno 

### ISSUE THREAD

**Issue by letMarchezi** [letMarchezi/isf-pibd#9]
Apesar de registrar nota de atividade, não estamos salvando a situação final do aluno na disciplina de especialização.. O que acham de criar um atributo para salvar se o aluno a situação do aluno? Por exemplo: cancelado, evadido, reprovado, aprovado.

![is1](https://github.com/letMarchezi/isf-pibd/assets/39420862/e56a66dc-39e0-4b31-b0cb-9d029afd4b64)

**Comment by DanielKenichi** [comment]
Acho que pode ser sim, ai seria um atributo da relação cursa certo?

**Comment by letMarchezi** [comment]
simm isso mesmo

**Comment by DanielKenichi** [comment]
Acredito que pode seguir com essa abordagem
